import "@/styles/globals.css"

import { GeistSans } from "geist/font/sans"
import { GeistMono } from "geist/font/mono"
import { type Metadata } from "next"
import { Navbar } from "./_components/navbar"

export const metadata: Metadata = {
  title: "practish - Practice your shell",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
}

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable} ${GeistMono.variable}`}>
      <body className="font-geist flex-col flex h-screen">
        <Navbar />
        <div className="flex-grow p-4">
          {children}
        </div>
      </body>
    </html>
  )
}
